steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.migration', '-t', 'gcr.io/chinese-website-482900/migrate-japanese:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/chinese-website-482900/migrate-japanese:latest']
images:
  - 'gcr.io/chinese-website-482900/migrate-japanese:latest'
